# Generated by Django 4.2.1 on 2023-06-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Email',
            new_name='email',
        ),
    ]
